### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by etclub** [mweidner037/list-positions#26]
I am trying this repo in a project with vite.
It reports error
```
|- SyntaxError: [vite] Named export 'OutlineSavedState' not found. The requested module 'list-positions' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'list-positions';
const {OrderSavedState, OutlineSavedState} = pkg;
```

**Comment by mweidner037** [comment]
Is the error occurring in your code or in one of the library's files? If
it's your code, try using `import type` instead of `import` for those names
(both are TypeScript interfaces). Apparently Vite makes that necessary:
https://stackoverflow.com/a/77465121

**Comment by etclub** [comment]
I see.
So I just remove them as I am not using typescript.
