### ISSUE TITLE
List.saveOutline / loadOutline

### ISSUE THREAD

**Issue by mweidner037** [mweidner037/list-positions#8]
It would be nice if you could save/load a List as an OutlineSavedState + literal values array. This is convenient for searching data at rest, and in the benchmarks, it looks like gzipping those two separately will be smaller than gzipping the ListSavedState.

I'm imagining the following methods on List:
```ts
saveOutline(): OutlineSavedState;

loadOutline(savedState: OutlineSavedState, values: T[]): void;
```
where you can save the values using `list.slice()`.

**Comment by mweidner037** [comment]
Once we have this, it's possible to convert between (saved states for) List, LexList, and Outline. This should be documented in a "Compatibility" section of the readme.

**Comment by scottmessinger** [comment]
I’m probably missing something obvious in the docs, but why does load take the return of the save function AND  a list of values? What would those values be?

**Comment by mweidner037** [comment]
@scottmessinger The idea behind these methods is to let you save the CRDT metadata (encoded by the OutlineSavedState) separately from the actual list values, so that you can store the values in your own format. E.g., store text data as a normal text file, so that it is easy to search. But then when you reconstruct the `List<T>` later, it needs both the CRDT metadata and the values.
